### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by LoisGNS** [MrTyton/AutomatedFanfic#1] opened 2020-12-22 10:30 UTC
From the fanficfare page. Please excuse all the noob questions - I'm not a Python developer. 
I see that several of the files have been updated, and that I need Python 3.6.9 (I currently have 2.7, which I set up some years ago when I thought I might teach myself Python - but never got around to it.) Anyway, I went to python.org and found a download page for Python 3.6.9, where they provide only source code, which I have no way of compiling (looks like it compiles with c ?). The closest version with an installer was 3.7.3, so I set that up. 

What do I do next? I downloaded the files from the Code page and put them in the Scripts folder of the Python37 install. I tried, from that folder, invoking fanficdownload.py, and it displayed a message that it was "preparing to configure" my Python 27 installation - which seemed odd, so I canceled out of that.

**Comment by MrTyton** [comment] 2020-12-22 10:33
What operating system are you running on? And would you mind copying the entirety of the output?

**Comment by LoisGNS** [comment] 2020-12-22 10:49
Windows 7 Professional 64 bit. Not sure what you mean by the output. I copied your files to c:\python37\scripts, then typed "fanficdownload.py". I get a opoup window "ActivePython 2.7.13 Build 2716 (64 bit)" with contents "Please wait while Windows configures ActivePython 2.7.13 Build 2716 (64 bit)." I click "cancel" and the message is now "C:\python37\scripts\fanficdownload.py  User cancelled installation."

I currently have both Python27 and Python37 installed, and (depending on where I look) one, the other, or both might be in my path.

**Comment by MrTyton** [comment] 2020-12-22 11:05
Make sure that you run it with python 3. Systems can be weird about which
they're running with, you might have to specify python3 instead of just
using python. Failing that, try looking into anaconda to get a more windows
friendly python build.

**Comment by LoisGNS** [comment] 2020-12-23 01:15
I can run "fanficdownload.py" from a command line  - issues as already described. How to I run it "with" python 3? When I run the python 3.73 I installed, it gives me a terminal window. In the terminal window, I type "fanficdownload" or "fanficdownload.py" or .\scripts\fanficdownload.py (since it is located in python37\scripts) - each one produces an error message pertaining to line 1. 

I also tried "python .\scripts\fanficdownload.py", which produces an error on line 2:
C:\Python37>python .\scripts\fanficdownload.py >> errs.txt
Traceback (most recent call last):
  File ".\scripts\fanficdownload.py", line 2, in <module>
    from os import listdir, remove, rename, utime, errno, devnull
ImportError: cannot import name 'errno' from 'os' (C:\Python37\lib\os.py)

Using "python3" instead of "python" in the command  line simply results in non-recognition of "python3," since the executable is indeed called "python." In case there's a path-related ambiguity with another version of Python, I renamed python.exe to python37.exe and ran the command with that in place of "python." Same error.

Keeping in mind that I really don't know my way around Python, what command should I be issuing either at the "DOS" command box or inside the Python terminal?

**Comment by MrTyton** [comment] 2023-01-06 00:22
Closing, since now there is a docker file.

**Comment by LoisGNS** [comment] 2023-01-06 00:53
Well, that doesn't help me, since I don't use docker. Is there a way I can use this just from Windows or should I give up on this? It would still be good to have some actual instructions for use (or if there are any, point to their location, since I was unable to find.).

**Comment by MrTyton** [comment] 2023-01-06 01:01
Do you want to just run it once or run it on a schedule? Instructions will differ for both.

**Comment by LoisGNS** [comment] 2023-01-06 01:31
I would run it as needed, but not on a set schedule.

**Comment by MrTyton** [comment] 2024-05-28 02:02
Updated readme with links and information, sorry for the delay. If the instructions are still unclear, please state.

My recommendation if you want to run it as needed is to just run it and close out when it's done, as right now it will auto loop.

**Closed by MrTyton** 2024-05-28 02:02 UTC

**Comment by MrTyton** [comment] 2025-10-02 23:43
## Status Update - October 2, 2025

**Current Status:** 🔄 Testing simplified conditional logic

**Changes Made (Commit \27f8dcb\):**
- Simplified \uild_docker\ job condition to only check \changes_detected == 'true'\
- Removed redundant \commit_sha != ''\ check  
- Updated job output to use \commit_changes.outputs.commit_long_sha\ directly

**Testing Plan:**
- ⏳ **Next scheduled run:** October 3, 2025 at 23:00 UTC
- ✅ **Manual trigger test:** Confirmed workflow skips correctly when no changes detected
- 📋 **Success criteria:** If dependency updates are found, both \uild_matrix\ and \merge_and_release\ jobs should execute

**Monitoring Commands:**
\\\ash
# Check latest workflow runs
gh run list --workflow=update-dependencies.yml --limit 5

# Monitor specific run when it happens
gh run view <run_id> --log
\\\

Will update this issue with results from the next automatic run.
